"""- thresholds
- defaults
"""

VISIBILITY_BRIGHTNESS_THRESHOLD = 80
TRAFFIC_RED_THRESHOLD = 1.2
TRAFFIC_GREEN_THRESHOLD = 1.1
CONTOUR_AREA_NEAR = 5000
CONTOUR_AREA_MEDIUM = 1500

DEFAULT_ACTION_ON_ERROR = "SLOW_DOWN"
DEFAULT_ACTION_ON_MISSING = "SLOW_DOWN"
